# TODO:
#  1. Test and Fix issues in Dockerfile

## Stage: Build driver
FROM quay.io/wangzheng422/qimgs:mofed-wzh-5.2-2.2.0.0-2021-03-30-1331-bclinux7.6-amd64-build AS build

# RUN yum -y install sysvinit-tools
COPY mlx.repo /etc/yum.repos.d/

RUN yum -y install infiniband-diags opensm

WORKDIR /
ADD ./entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh

ENTRYPOINT ["/root/entrypoint.sh"]
